fetch("https://chat.openai.com/backend-api/conversation", {
  "headers": {
    "accept": "text/event-stream",
    "accept-language": "en-US,en;q=0.9",
    "authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJhbnRob25pbmNvbGFzcHJvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLUk4MmZWVEVXN0xSTGx4RTBJQTdiSFB0MyJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTE2NDY5NzE3MTI0NTExNjcxMjgiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjgzMjk2MzUxLCJleHAiOjE2ODQ1MDU5NTEsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb2ZmbGluZV9hY2Nlc3MifQ.EExw8iWICWp0YsflFeIlm5vxhTR1-S2GDOogUmA2JTDXUi_Ws6_L8R-1c1xUOUNWYZoIiU8Xypn28U4P5tCvWXthlcWUNV8gMEbSHlrsrIbxFhaxF4uARR9HmaGmxIQogSrQ48yd19oYbxm8ZJJK8L3TU0gsP5crAkauB_O4xOhhAFyaRNxtP58-gQgkBqEY2fMW_0NVAd2aJLDj380rw0fN_VGmTblLL42nR1lZ4-VMDJ0dzhSt167CNh9RtqYzuzT5mCPeIPL6_D9YWpDCJvpobZBwSt61qXz2D0OkY1S--poUdMwp4u_hLVXkcBv_giEAdxSGqp43T4eW2CHNQQ",
    "content-type": "application/json",
    "sec-ch-ua": "\"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "https://chat.openai.com/c/6af0214a-2f36-4956-9a3c-f43caca6d92a",
  "referrerPolicy": "same-origin",
  "body": "{\"action\":\"variant\",\"messages\":[{\"id\":\"aaa2bc4d-7b79-48b4-ab92-ebf18c86c231\",\"author\":{\"role\":\"user\",\"metadata\":{}},\"create_time\":1682778961.4057,\"content\":{\"content_type\":\"text\",\"parts\":[\"est ce que je peut attendre le démarrage du process de mysql avant de lancer le serveur ? j'ai changé le script et rajoute quelque ligne check ça : \\n\\n#!/bin/bash\\n\\n# Define color codes\\nRED=\\\"\\\\033[0;31m\\\"\\nGREEN=\\\"\\\\033[0;32m\\\"\\nYELLOW=\\\"\\\\033[1;33m\\\"\\nBLUE=\\\"\\\\033[0;34m\\\"\\nNC=\\\"\\\\033[0m\\\" # No Color\\n\\n# Define emojis\\nINFO_EMOJI=\\\"ℹ️\\\"\\nCHECK_MARK_EMOJI=\\\"✅\\\"\\nWARNING_EMOJI=\\\"⚠️\\\"\\nQUESTION_EMOJI=\\\"❓\\\"\\n\\ninstall_dependencies() {\\n  # Check if Homebrew is installed\\n  if ! command -v brew >/dev/null 2>&1; then\\n    echo -e \\\"${YELLOW}${QUESTION_EMOJI}${NC} Homebrew is not installed. Would you like to install it now? (y/n)\\\"\\n    read -r answer\\n    if [ \\\"$answer\\\" = \\\"y\\\" ] || [ \\\"$answer\\\" = \\\"Y\\\" ]; then\\n      echo -e \\\"${BLUE}${INFO_EMOJI}${NC} Installing Homebrew...\\\"\\n      /bin/bash -c \\\"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\\\"\\n    else\\n      echo -e \\\"${WARNING_EMOJI} Skipping Homebrew installation\\\"\\n    fi\\n  else\\n    echo -e \\\"${GREEN}${CHECK_MARK_EMOJI}${NC} Homebrew is already installed\\\"\\n  fi\\n\\n  # Check if MySQL is installed\\n  if ! command -v mysql >/dev/null 2>&1; then\\n    echo -e \\\"${YELLOW}${QUESTION_EMOJI}${NC} MySQL is not installed. Would you like to install it now? (y/n)\\\"\\n    read -r answer\\n    if [ \\\"$answer\\\" = \\\"y\\\" ] || [ \\\"$answer\\\" = \\\"Y\\\" ]; then\\n      echo -e \\\"${BLUE}${INFO_EMOJI}${NC} Installing MySQL...\\\"\\n      brew install mysql\\n    else\\n      echo -e \\\"${WARNING_EMOJI} Skipping MySQL installation\\\"\\n    fi\\n  else\\n    echo -e \\\"${GREEN}${CHECK_MARK_EMOJI}${NC} MySQL is already installed\\\"\\n  fi\\n}\\n(install_dependencies)\\nwait\\n\\n# Check if MySQL is running\\nMYSQL_PROCESS_COUNT=$(pgrep mysqld | wc -l)\\n\\n# Start MySQL server if it's not running\\nif [ $MYSQL_PROCESS_COUNT -eq 0 ]; then\\n  echo \\\"Starting MySQL server...\\\"\\n  mysql.server start\\nelse\\n  echo \\\"MySQL server is already running\\\"\\nfi\\n\\nconcurrently \\\"yarn dev:client\\\" \\\"yarn dev:server\\\"\\n\"]},\"weight\":1,\"metadata\":{\"timestamp_\":\"absolute\"},\"recipient\":\"all\"}],\"conversation_id\":\"6af0214a-2f36-4956-9a3c-f43caca6d92a\",\"parent_message_id\":\"3bb6a76d-1163-4fba-88e1-dfd3508ca453\",\"model\":\"gpt-4\",\"timezone_offset_min\":-120,\"variant_purpose\":\"none\",\"history_and_training_disabled\":false}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});